### ISSUE TITLE
Responder en archivo de texto: # Que esel Product Backlog? 

### ISSUE THREAD

**Issue by CaronlineArg** [CaronlineArg/ISPCGrupoAula24Beta#7]
El archivo se encuentra en el repositorio: https://github.com/CaronlineArg/ISPCGrupoAula24Beta

Notas adicionales
--------------------------
Corregir la  pregunta: lleva un espacio entre las palabras ´es´ y ´el´

**Comment by julieta-10-stor** [comment]
Hola acá te envió la respuesta de esta pregunta:  
¿Qué es el PRODUCT BACKLOG?
El Product Backlog (o “Lista de Producto” en español) es una lista emergente y ordenada de todo lo que se conoce que es necesario que un producto o servicio cumpla. Siendo una única fuente de requisitos para cualquier cambio. también es dinámico cambia a cada rato identificando el producto para ser competitivo y útil en el mercado del mundo en donde se encuentre.
